const { expect } = require('chai')
const { ethers } = require('hardhat')
const fixture = require('./fixtures/xec-block-959170.json')

// Validates MerkleProof.sol and Difficulty.sol against a real, mined XEC block
// (height 959170, fetched from ecash.badger.cash), not just synthetic data --
// the fixture was generated by packages/sdk's own buildMerkleProof/Block.fromJSON
// against that block's real JSON representation (see the header comment in the
// fixture-generating script kept alongside this session's scratch files).
describe('MerkleProof / Difficulty against a real XEC block', function () {
  let harness

  before(async function () {
    const Harness = await ethers.getContractFactory('TestHarness')
    harness = await Harness.deploy()
    await harness.deployed()
  })

  it("recomputes the header's bits field correctly", async function () {
    const bits = await harness.headerBits('0x' + fixture.rawHeader)
    expect(bits).to.equal(fixture.bits)
  })

  it("recomputes the header's own hash, matching the explorer's reported hash (display order)", async function () {
    const hash = await harness.headerHash('0x' + fixture.rawHeader)
    const displayOrder = Buffer.from(hash.slice(2), 'hex').reverse().toString('hex')
    expect(displayOrder).to.equal(fixture.expectedHash)
  })

  it("recomputes the header's merkle root, matching the explorer's reported root (display order)", async function () {
    const root = await harness.headerMerkleRoot('0x' + fixture.rawHeader)
    const displayOrder = Buffer.from(root.slice(2), 'hex').reverse().toString('hex')
    expect(displayOrder).to.equal(fixture.expectedMerkleRoot)
  })

  it('a real, validly-mined header satisfies its own implied difficulty target', async function () {
    // A real header must, by definition, hash below the target implied by its own
    // `bits` -- if bitsToTarget/hashToUint were wrong, this would fail even though
    // the block is genuinely valid.
    const veryPermissiveFloor = ethers.BigNumber.from(2).pow(256).sub(1)
    const ok = await harness.meetsFloor('0x' + fixture.rawHeader, veryPermissiveFloor)
    expect(ok).to.equal(true)
  })

  it('meetsFloor rejects when the floor is set stricter (lower) than the header actually clears', async function () {
    const target = await harness.bitsToTarget(fixture.bits)
    const strictFloor = target.div(2) // require twice the real difficulty
    const ok = await harness.meetsFloor('0x' + fixture.rawHeader, strictFloor)
    expect(ok).to.equal(false)
  })

  it('verifies a real Merkle proof built by packages/sdk against this real block', async function () {
    const ok = await harness.merkleVerify(
      '0x' + fixture.txid,
      fixture.branch.map((h) => '0x' + h),
      fixture.index,
      '0x' + fixture.root
    )
    expect(ok).to.equal(true)
  })

  it('rejects the same proof against a tampered root', async function () {
    const wrongRoot = '0x' + '11'.repeat(32)
    const ok = await harness.merkleVerify(
      '0x' + fixture.txid,
      fixture.branch.map((h) => '0x' + h),
      fixture.index,
      wrongRoot
    )
    expect(ok).to.equal(false)
  })
})
